package com.example.nzoz.demonzoz.util;

import com.google.common.collect.ImmutableMap;
import java.util.Map;

public class SpecialityMap {
  public static final Map<String, String> SPECIALITY_MAP = ImmutableMap.<String, String>builder()
      .put("fizjoterapeuta", "Dział (pracownia) fizjoterapii")
      .put("fizjoterapeuta dziecięcy", "Dział (pracownia) fizjoterapii dla dzieci")
      .put("masażysta", "Dział (pracownia) masażu leczniczego")
      .put("masażysta dziecięcy", "Dział (pracownia) masażu leczniczego dla dzieci")
      .put("orzecznik", "Dział orzecznictwa o stanie zdrowia")
      .put("geriatra", "Dzienny ośrodek opieki geriatrycznej")
      .put("psychiatra dziecięcy", "Oddział dzienny psychiatryczny (ogólny) dla dzieci")
      .put("pulmunolog", "Oddział rehabilitacji pulmonologicznej")
      .put("rehabilitant", "Ośrodek rehabilitacji dziennej")
      .put("pielęgniarka", "Pielęgniarska opieka długoterminowa domowa")
      .put("ogólny", "Poradnia (gabinet) lekarza podstawowej opieki zdrowotnej")
      .put("internista", "Poradnia (gabinet) lekarza podstawowej opieki zdrowotnej")
      .put("poz", "Poradnia (gabinet) lekarza podstawowej opieki zdrowotnej")
      .put("położna", "Poradnia (gabinet) położnej podstawowej opieki zdrowotnej")
      .put("alergolog", "Poradnia alergologiczna")
      .put("androlog", "Poradnia andrologiczna")
      .put("audiolog", "Poradnia audiologiczna")
      .put("chirurg naczyniowy", "Poradnia chirurgii naczyniowej")
      .put("chirurg", "Poradnia chirurgii ogólnej")
      .put("chirurg dziecięcy", "Poradnia chirurgii ogólnej dla dzieci")
      .put("onkolog", "Poradnia chirurgii onkologicznej")
      .put("stomatolog", "Poradnia chirurgii stomatologicznej")
      .put("ortopeda", "Poradnia chirurgii urazowo-ortopedycznej")
      .put("ortopeda dziecięcy", "Poradnia chirurgii urazowo-ortopedycznej dla dzieci")
      .put("pulmunolog dziecięcy", "Poradnia chorób płuc dla dzieci")
      .put("internista dziecięcy", "Poradnia chorób wewnętrznych dla dzieci")
      .put("dermatolog", "Poradnia dermatologiczna")
      .put("diabetolog", "Poradnia diabetologiczna")
      .put("diabetolog dziecięcy", "Poradnia diabetologiczna dla dzieci")
      .put("endokrynolog", "Poradnia endokrynologiczna")
      .put("endokrynolog dziecięcy", "Poradnia endokrynologiczna dla dzieci")
      .put("ginekolog", "Poradnia ginekologiczna")
      .put("foniatra", "Poradnia foniatryczna")
      .put("gastroenterolog", "Poradnia gastroenterologiczna")
      .put("gastroenterolog dziecięcy", "Poradnia gastroenterologiczna dla dzieci")
      .put("ginekolog dziecięcy", "Poradnia ginekologiczna dla dziewcząt")
      .put("hematolog", "Poradnia hematologiczna")
      .put("hepatolog", "Poradnia hepatologiczna")
      .put("immunolog", "Poradnia immunologiczna")
      .put("kardiochirurg", "Poradnia kardiochirurgiczna")
      .put("kardiolog", "Poradnia kardiologiczna")
      .put("doradca laktacyjny", "Poradnia laktacyjna")
      .put("logopeda", "Poradnia logopedyczna")
      .put("logopeda dziecięcy", "Poradnia logopedyczna dla dzieci")
      .put("nefrolog", "Poradnia nefrologiczna")
      .put("nefrolog dziecięcy", "Poradnia nefrologiczna dla dzieci")
      .put("neonatolog", "Poradnia neonatologiczna")
      .put("neurochirurg", "Poradnia neurochirurgiczna")
      .put("neurolog", "Poradnia neurologiczna")
      .put("neurolog dziecięcy", "Poradnia neurologiczna dla dzieci")
      .put("okulista", "Poradnia okulistyczna")
      .put("ortodonta", "Poradnia ortodontyczna")
      .put("otolaryngolog", "Poradnia otorynolaryngologiczna")
      .put("otolaryngolog dziecięcy", "Poradnia otorynolaryngologiczna dla dzieci")
      .put("pediatra", "Poradnia pediatryczna")
      .put("położnik", "Poradnia położniczo-ginekologiczna")
      .put("proktolog", "Poradnia proktologiczna")
      .put("psycholog", "Poradnia psychologiczna")
      .put("reumatolog", "Poradnia reumatologiczna")
      .put("reumatolog dziecięcy", "Poradnia reumatologiczna dla dzieci")
      .put("stomatolog dziecięcy", "Poradnia stomatologiczna dla dzieci")
      .put("urolog", "Poradnia urologiczna")
      .put("psychiatra", "Poradnia zdrowia psychicznego")
      .build();
}
